-- Links stop being deleted, and start having a lifetime.
--
-- ontology_link_instances had created_at and nothing else, so the ontology
-- could answer "when did this patient arrive on the ward" and never "when did
-- they leave" — removal was a real DELETE and the row was gone. That makes
-- occupancy at any past moment unanswerable: you can count the links created
-- before a time, but not subtract the ones removed before it.
--
-- Recording starts now because history not recorded is history that cannot be
-- had later. Reading it comes in a later phase; nothing queries valid_to yet.

ALTER TABLE app.ontology_link_instances
    ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS valid_to   TIMESTAMPTZ NULL;

-- Existing rows have always been true since they were created.
UPDATE app.ontology_link_instances
   SET valid_from = created_at
 WHERE valid_from > created_at;

-- The uniqueness rule changes meaning: one *live* link per triple, but any
-- number of historical ones. Without this, a patient who leaves a ward and
-- comes back cannot be re-linked — the closed row still occupies the key.
--
-- The old constraint name was generated by Postgres and truncated at 63 chars,
-- so it is found by shape rather than guessed at.
DO $$
DECLARE
    v_name TEXT;
BEGIN
    SELECT c.conname INTO v_name
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
     WHERE n.nspname = 'app'
       AND t.relname = 'ontology_link_instances'
       AND c.contype = 'u'
     LIMIT 1;
    IF v_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE app.ontology_link_instances DROP CONSTRAINT %I', v_name);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ontology_link_instances_live_key
    ON app.ontology_link_instances (link_type_id, from_instance_id, to_instance_id)
 WHERE valid_to IS NULL;

-- Reads at a past instant filter on the open interval; both bounds get an index
-- because "still open" and "closed before T" are the two shapes of that query.
CREATE INDEX IF NOT EXISTS ontology_link_instances_valid_idx
    ON app.ontology_link_instances (valid_from, valid_to);

CREATE INDEX IF NOT EXISTS ontology_link_instances_open_idx
    ON app.ontology_link_instances (link_type_id, from_instance_id)
 WHERE valid_to IS NULL;
